jwt:
  secret: javainuse
spring:
  datasource:
    password: Maya@9977
    url: jdbc:sqlserver://performr.database.windows.net:1433;database=performr;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: abhi
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
